export interface ElementDetail {
  number: number;
  symbol: string;
  name: string;
  mass: number;
  category: 'alkali' | 'alkaline' | 'transition' | 'post-transition' | 'metalloid' | 'nonmetal' | 'halogen' | 'noble' | 'lanthanide' | 'actinide';
  group: number;
  period: number;
  block: 's' | 'p' | 'd' | 'f';
  electronegativity: number;
  electronConfig: string;
  atomicRadius: number; // pm
  ionizationEnergy: number; // kJ/mol
  oxidationStates: string;
  density: number; // g/cm³
  stateAtRoom: 'gas' | 'liquid' | 'solid';
  summary: string;
}

export const periodicTableElements: ElementDetail[] = [
  { number: 1, symbol: 'H', name: 'Hydrogen', mass: 1.008, category: 'nonmetal', group: 1, period: 1, block: 's', electronegativity: 2.20, electronConfig: '1s¹', atomicRadius: 37, ionizationEnergy: 1312, oxidationStates: '+1, -1', density: 0.00008988, stateAtRoom: 'gas', summary: 'Lightest chemical element; highly flammable diatomic gas.' },
  { number: 2, symbol: 'He', name: 'Helium', mass: 4.0026, category: 'noble', group: 18, period: 1, block: 's', electronegativity: 0, electronConfig: '1s²', atomicRadius: 32, ionizationEnergy: 2372, oxidationStates: '0', density: 0.0001785, stateAtRoom: 'gas', summary: 'Colorless, odorless noble gas with lowest boiling point.' },
  { number: 3, symbol: 'Li', name: 'Lithium', mass: 6.94, category: 'alkali', group: 1, period: 2, block: 's', electronegativity: 0.98, electronConfig: '[He] 2s¹', atomicRadius: 152, ionizationEnergy: 520, oxidationStates: '+1', density: 0.534, stateAtRoom: 'solid', summary: 'Soft, silvery alkali metal; lightest solid element.' },
  { number: 4, symbol: 'Be', name: 'Beryllium', mass: 9.0122, category: 'alkaline', group: 2, period: 2, block: 's', electronegativity: 1.57, electronConfig: '[He] 2s²', atomicRadius: 112, ionizationEnergy: 899, oxidationStates: '+2', density: 1.85, stateAtRoom: 'solid', summary: 'Relatively rare metal in universe; forms Emerald gemstones.' },
  { number: 5, symbol: 'B', name: 'Boron', mass: 10.81, category: 'metalloid', group: 13, period: 2, block: 'p', electronegativity: 2.04, electronConfig: '[He] 2s² 2p¹', atomicRadius: 85, ionizationEnergy: 801, oxidationStates: '+3', density: 2.34, stateAtRoom: 'solid', summary: 'Low-abundance metalloid used in fiberglass and semiconductors.' },
  { number: 6, symbol: 'C', name: 'Carbon', mass: 12.011, category: 'nonmetal', group: 14, period: 2, block: 'p', electronegativity: 2.55, electronConfig: '[He] 2s² 2p²', atomicRadius: 77, ionizationEnergy: 1086, oxidationStates: '+4, +2, -4', density: 2.267, stateAtRoom: 'solid', summary: 'Basis of organic life; forms graphite, diamond, and graphene.' },
  { number: 7, symbol: 'N', name: 'Nitrogen', mass: 14.007, category: 'nonmetal', group: 15, period: 2, block: 'p', electronegativity: 3.04, electronConfig: '[He] 2s² 2p³', atomicRadius: 75, ionizationEnergy: 1402, oxidationStates: '+5, +3, -3', density: 0.001251, stateAtRoom: 'gas', summary: 'Makes up 78% of Earth atmosphere; essential component of amino acids.' },
  { number: 8, symbol: 'O', name: 'Oxygen', mass: 15.999, category: 'nonmetal', group: 16, period: 2, block: 'p', electronegativity: 3.44, electronConfig: '[He] 2s² 2p⁴', atomicRadius: 73, ionizationEnergy: 1314, oxidationStates: '-2', density: 0.001429, stateAtRoom: 'gas', summary: 'Highly reactive nonmetal; essential for cellular respiration.' },
  { number: 9, symbol: 'F', name: 'Fluorine', mass: 18.998, category: 'halogen', group: 17, period: 2, block: 'p', electronegativity: 3.98, electronConfig: '[He] 2s² 2p⁵', atomicRadius: 71, ionizationEnergy: 1681, oxidationStates: '-1', density: 0.001696, stateAtRoom: 'gas', summary: 'Most electronegative chemical element; extremely toxic pale yellow gas.' },
  { number: 10, symbol: 'Ne', name: 'Neon', mass: 20.180, category: 'noble', group: 18, period: 2, block: 'p', electronegativity: 0, electronConfig: '[He] 2s² 2p⁶', atomicRadius: 69, ionizationEnergy: 2081, oxidationStates: '0', density: 0.0009002, stateAtRoom: 'gas', summary: 'Glows reddish-orange in high-voltage electrical discharge signs.' },
  { number: 11, symbol: 'Na', name: 'Sodium', mass: 22.990, category: 'alkali', group: 1, period: 3, block: 's', electronegativity: 0.93, electronConfig: '[Ne] 3s¹', atomicRadius: 186, ionizationEnergy: 496, oxidationStates: '+1', density: 0.968, stateAtRoom: 'solid', summary: 'Soft, silvery-white alkali metal; component of table salt (NaCl).' },
  { number: 12, symbol: 'Mg', name: 'Magnesium', mass: 24.305, category: 'alkaline', group: 2, period: 3, block: 's', electronegativity: 1.31, electronConfig: '[Ne] 3s²', atomicRadius: 160, ionizationEnergy: 738, oxidationStates: '+2', density: 1.738, stateAtRoom: 'solid', summary: 'Shiny gray solid; key metal in chlorophyll and structural alloys.' },
  { number: 13, symbol: 'Al', name: 'Aluminium', mass: 26.982, category: 'post-transition', group: 13, period: 3, block: 'p', electronegativity: 1.61, electronConfig: '[Ne] 3s² 3p¹', atomicRadius: 143, ionizationEnergy: 578, oxidationStates: '+3', density: 2.70, stateAtRoom: 'solid', summary: 'Abundant low-density metal; highly resistant to corrosion.' },
  { number: 14, symbol: 'Si', name: 'Silicon', mass: 28.085, category: 'metalloid', group: 14, period: 3, block: 'p', electronegativity: 1.90, electronConfig: '[Ne] 3s² 3p²', atomicRadius: 118, ionizationEnergy: 787, oxidationStates: '+4, -4', density: 2.329, stateAtRoom: 'solid', summary: 'Hard, brittle crystalline solid; fundamental semiconductor for microchips.' },
  { number: 15, symbol: 'P', name: 'Phosphorus', mass: 30.974, category: 'nonmetal', group: 15, period: 3, block: 'p', electronegativity: 2.19, electronConfig: '[Ne] 3s² 3p³', atomicRadius: 110, ionizationEnergy: 1012, oxidationStates: '+5, +3, -3', density: 1.823, stateAtRoom: 'solid', summary: 'Exists in white, red, and black allotropes; vital for DNA and ATP.' },
  { number: 16, symbol: 'S', name: 'Sulfur', mass: 32.06, category: 'nonmetal', group: 16, period: 3, block: 'p', electronegativity: 2.58, electronConfig: '[Ne] 3s² 3p⁴', atomicRadius: 103, ionizationEnergy: 1000, oxidationStates: '+6, +4, -2', density: 2.07, stateAtRoom: 'solid', summary: 'Bright yellow crystalline solid at room temperature; component of amino acids.' },
  { number: 17, symbol: 'Cl', name: 'Chlorine', mass: 35.45, category: 'halogen', group: 17, period: 3, block: 'p', electronegativity: 3.16, electronConfig: '[Ne] 3s² 3p⁵', atomicRadius: 99, ionizationEnergy: 1251, oxidationStates: '+7, +5, +1, -1', density: 0.003214, stateAtRoom: 'gas', summary: 'Yellow-green halogen gas; strong disinfectant and oxidizer.' },
  { number: 18, symbol: 'Ar', name: 'Argon', mass: 39.948, category: 'noble', group: 18, period: 3, block: 'p', electronegativity: 0, electronConfig: '[Ne] 3s² 3p⁶', atomicRadius: 97, ionizationEnergy: 1521, oxidationStates: '0', density: 0.001784, stateAtRoom: 'gas', summary: 'Third most abundant gas in Earth atmosphere; inert shielding gas.' },
  { number: 19, symbol: 'K', name: 'Potassium', mass: 39.098, category: 'alkali', group: 1, period: 4, block: 's', electronegativity: 0.82, electronConfig: '[Ar] 4s¹', atomicRadius: 227, ionizationEnergy: 419, oxidationStates: '+1', density: 0.89, stateAtRoom: 'solid', summary: 'Essential nutrient for nerve transmission and electrolyte balance.' },
  { number: 20, symbol: 'Ca', name: 'Calcium', mass: 40.078, category: 'alkaline', group: 2, period: 4, block: 's', electronegativity: 1.00, electronConfig: '[Ar] 4s²', atomicRadius: 197, ionizationEnergy: 590, oxidationStates: '+2', density: 1.55, stateAtRoom: 'solid', summary: 'Fifth most abundant element in Earth crust; essential for bones and teeth.' },
  { number: 26, symbol: 'Fe', name: 'Iron', mass: 55.845, category: 'transition', group: 8, period: 4, block: 'd', electronegativity: 1.83, electronConfig: '[Ar] 3d⁶ 4s²', atomicRadius: 126, ionizationEnergy: 763, oxidationStates: '+2, +3', density: 7.874, stateAtRoom: 'solid', summary: 'Most common element on Earth by mass; primary component of steel.' },
  { number: 29, symbol: 'Cu', name: 'Copper', mass: 63.546, category: 'transition', group: 11, period: 4, block: 'd', electronegativity: 1.90, electronConfig: '[Ar] 3d¹⁰ 4s¹', atomicRadius: 128, ionizationEnergy: 745, oxidationStates: '+1, +2', density: 8.96, stateAtRoom: 'solid', summary: 'Soft, malleable metal with high electrical and thermal conductivity.' },
  { number: 30, symbol: 'Zn', name: 'Zinc', mass: 65.38, category: 'transition', group: 12, period: 4, block: 'd', electronegativity: 1.65, electronConfig: '[Ar] 3d¹⁰ 4s²', atomicRadius: 134, ionizationEnergy: 906, oxidationStates: '+2', density: 7.14, stateAtRoom: 'solid', summary: 'Essential trace mineral; used to galvanize steel against rust.' },
  { number: 35, symbol: 'Br', name: 'Bromine', mass: 79.904, category: 'halogen', group: 17, period: 4, block: 'p', electronegativity: 2.96, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', atomicRadius: 114, ionizationEnergy: 1140, oxidationStates: '+5, +1, -1', density: 3.102, stateAtRoom: 'liquid', summary: 'Fuming red-brown liquid nonmetal at room temperature.' },
  { number: 47, symbol: 'Ag', name: 'Silver', mass: 107.87, category: 'transition', group: 11, period: 5, block: 'd', electronegativity: 1.93, electronConfig: '[Kr] 4d¹⁰ 5s¹', atomicRadius: 144, ionizationEnergy: 731, oxidationStates: '+1', density: 10.49, stateAtRoom: 'solid', summary: 'Highest electrical conductivity, thermal conductivity, and reflectivity of any metal.' },
  { number: 79, symbol: 'Au', name: 'Gold', mass: 196.97, category: 'transition', group: 11, period: 6, block: 'd', electronegativity: 2.54, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', atomicRadius: 144, ionizationEnergy: 890, oxidationStates: '+1, +3', density: 19.30, stateAtRoom: 'solid', summary: 'Precious noble metal; highly resistant to corrosion and oxidation.' },
];
