import type { EquationEntry, Topic, Subject } from './types';

export const equationRegistry: EquationEntry[] = [
  // ── MECHANICS ──────────────────────────────────────────
  {
    id: 'newton-second-law',
    latex: 'F = ma',
    aliases: ['f=ma', 'f = ma', 'force = mass * acceleration', 'newton second law', 'newtons second law', 'f=m*a', 'force'],
    displayName: "Newton's Second Law",
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'F', name: 'Force', unit: 'N', description: 'Net force applied', min: 0, max: 500, defaultValue: 15 },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Mass of object', min: 0.1, max: 100, defaultValue: 5 },
      { symbol: 'a', name: 'Acceleration', unit: 'm/s²', description: 'Acceleration produced', min: 0, max: 50, defaultValue: 3 },
    ],
    explanation: "Newton's Second Law states that the net force on an object equals its mass times acceleration. F = ma.",
    explanation_beginner: "Push a heavy box and a light box equally hard — the light one moves faster! That's F = ma.",
    explanation_advanced: "The vector sum of all forces on a body equals the rate of change of its linear momentum: ΣF = dp/dt = ma for constant mass.",
    relatedEquations: ['momentum', 'weight', 'impulse', 'work'],
    simulationType: 'newton',
    availableActions: ['explain', 'visualize', 'simulate', 'practice', 'quiz', 'example'],
    jeeRelevance: 'JEE: Always draw FBD first. Net force = ma. Appears in every mechanics question.',
    prerequisites: ['velocity', 'acceleration'],
    tags: ['mechanics', 'force', 'newton', 'classical'],
  },
  {
    id: 'weight',
    latex: 'W = mg',
    aliases: ['w=mg', 'weight', 'gravitational force', 'w = mg', 'w=m*g', 'weight = mass * gravity'],
    displayName: 'Weight',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'W', name: 'Weight', unit: 'N', description: 'Gravitational force' },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Mass of object' },
      { symbol: 'g', name: 'Gravitational acceleration', unit: 'm/s²', description: '~9.8 on Earth', defaultValue: 9.8 },
    ],
    explanation: 'Weight is the gravitational force on an object: W = mg where g ≈ 9.8 m/s² on Earth.',
    explanation_beginner: 'Your weight is how hard gravity pulls you down. On the Moon, g is smaller so you weigh less!',
    explanation_advanced: "Weight is a vector force directed toward the center of mass of the attracting body. W = mg is valid near Earth's surface where g is approximately constant.",
    relatedEquations: ['newton-second-law', 'newton-gravitation'],
    simulationType: 'newton',
    availableActions: ['explain', 'simulate', 'example', 'quiz'],
    jeeRelevance: 'JEE: Distinguish mass (scalar, constant) from weight (vector, location-dependent).',
    prerequisites: ['newton-second-law'],
    tags: ['mechanics', 'gravity', 'weight'],
  },
  {
    id: 'momentum',
    latex: 'p = mv',
    aliases: ['p=mv', 'p = mv', 'momentum', 'linear momentum', 'p=m*v'],
    displayName: 'Linear Momentum',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'p', name: 'Momentum', unit: 'kg·m/s', description: 'Linear momentum' },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Mass' },
      { symbol: 'v', name: 'Velocity', unit: 'm/s', description: 'Velocity' },
    ],
    explanation: 'Momentum is the product of mass and velocity. It is a vector quantity.',
    explanation_beginner: 'A heavy truck moving slowly can have the same momentum as a small car moving fast.',
    explanation_advanced: "Linear momentum p = mv. Newton's 2nd law: F = dp/dt. Conservation: total momentum is conserved in isolated systems.",
    relatedEquations: ['newton-second-law', 'impulse', 'conservation-momentum'],
    simulationType: 'newton',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: p = mv, impulse-momentum theorem J = Δp, conservation in collisions.',
    prerequisites: ['newton-second-law'],
    tags: ['mechanics', 'momentum', 'vector'],
  },
  {
    id: 'power',
    latex: 'P = \\frac{W}{t}',
    aliases: ['p=w/t', 'p = w/t', 'power', 'power = work / time'],
    displayName: 'Mechanical Power',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'P', name: 'Power', unit: 'W', description: 'Rate of doing work' },
      { symbol: 'W', name: 'Work', unit: 'J', description: 'Work done' },
      { symbol: 't', name: 'Time', unit: 's', description: 'Time interval' },
    ],
    explanation: 'Power is the rate at which work is done or energy is transferred over time.',
    explanation_beginner: 'Doing the same work faster means using more power!',
    explanation_advanced: 'P = dW/dt = F·v. 1 Watt = 1 Joule per second. 1 horsepower ≈ 746 W.',
    relatedEquations: ['work', 'newton-second-law'],
    simulationType: 'newton',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Instantaneous power P = F·v. Average power P_avg = ΔW/Δt.',
    prerequisites: ['work'],
    tags: ['mechanics', 'power', 'work'],
  },
  {
    id: 'centripetal-force',
    latex: 'F_c = \\frac{mv^2}{r}',
    aliases: ['centripetal force', 'fc=mv2/r', 'fc = mv²/r', 'centripetal', 'f=mv^2/r', 'circular motion'],
    displayName: 'Centripetal Force',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'F_c', name: 'Centripetal Force', unit: 'N', description: 'Center-seeking force' },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Mass of object', defaultValue: 2 },
      { symbol: 'v', name: 'Velocity', unit: 'm/s', description: 'Tangential speed', defaultValue: 5 },
      { symbol: 'r', name: 'Radius', unit: 'm', description: 'Radius of circle', defaultValue: 3 },
    ],
    explanation: 'Net force directing an object along a circular path toward the center of curvature.',
    explanation_beginner: 'Swinging a ball on a string — your hand pulls inward to keep it moving in a circle.',
    explanation_advanced: 'a_c = v²/r = ω²r. F_c = m a_c = mv²/r = mω²r.',
    relatedEquations: ['newton-second-law', 'kinetic-energy'],
    simulationType: 'circular',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Banking of roads tanθ = v²/(rg). Minimum speed for vertical loop v = √(5gr).',
    prerequisites: ['newton-second-law'],
    tags: ['mechanics', 'circular', 'force'],
  },
  {
    id: 'torque',
    latex: '\\tau = r F \\sin\\theta',
    aliases: ['torque', 'tau=rxf', 'torque = r * f', 'tau = r f', 'tau=r f sin theta'],
    displayName: 'Torque (Rotational Force)',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'τ', name: 'Torque', unit: 'N·m', description: 'Rotational moment' },
      { symbol: 'r', name: 'Lever arm', unit: 'm', description: 'Distance from pivot', defaultValue: 1.5 },
      { symbol: 'F', name: 'Force', unit: 'N', description: 'Applied force', defaultValue: 20 },
      { symbol: 'θ', name: 'Angle', unit: '°', description: 'Angle to lever arm', defaultValue: 90 },
    ],
    explanation: 'Rotational equivalent of linear force measuring tendency to rotate an object about an axis.',
    explanation_beginner: 'Using a longer wrench makes it much easier to loosen a tight bolt!',
    explanation_advanced: 'τ⃗ = r⃗ × F⃗ = r F sinθ. τ = Iα (rotational analogue of F = ma).',
    relatedEquations: ['newton-second-law', 'work'],
    simulationType: 'torque',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Static equilibrium: ΣF = 0 and Στ = 0.',
    prerequisites: ['newton-second-law'],
    tags: ['mechanics', 'torque', 'rotation'],
  },
  {
    id: 'kinematic-v-u-at',
    latex: 'v = u + at',
    aliases: ['v=u+at', 'v = u + at', 'first equation of motion', '1st equation of motion'],
    displayName: '1st Equation of Motion',
    subject: 'physics',
    topic: 'kinematics',
    variables: [
      { symbol: 'v', name: 'Final velocity', unit: 'm/s', description: 'Velocity at time t' },
      { symbol: 'u', name: 'Initial velocity', unit: 'm/s', description: 'Initial velocity' },
      { symbol: 'a', name: 'Acceleration', unit: 'm/s²', description: 'Uniform acceleration' },
      { symbol: 't', name: 'Time', unit: 's', description: 'Time elapsed' },
    ],
    explanation: 'First equation of motion relating initial velocity, final velocity, acceleration, and time.',
    explanation_beginner: 'If you start at speed u and accelerate at rate a for time t, your final speed is v = u + at.',
    explanation_advanced: 'Derived by integrating a = dv/dt for constant acceleration: v = u + at.',
    relatedEquations: ['kinematic-s-ut', 'kinematic-v2-u2', 'projectile-range'],
    simulationType: 'projectile',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: One of 3 equations of motion. Use when s is not required.',
    prerequisites: ['velocity', 'acceleration'],
    tags: ['kinematics', 'motion', 'equations-of-motion'],
  },
  {
    id: 'kinematic-s-ut',
    latex: 's = ut + \\frac{1}{2}at^2',
    aliases: ['s=ut+1/2at2', 's = ut + ½at²', 'second equation of motion', '2nd equation of motion', 's=ut+0.5at^2'],
    displayName: '2nd Equation of Motion',
    subject: 'physics',
    topic: 'kinematics',
    variables: [
      { symbol: 's', name: 'Displacement', unit: 'm', description: 'Distance traveled' },
      { symbol: 'u', name: 'Initial velocity', unit: 'm/s', description: 'Initial velocity' },
      { symbol: 'a', name: 'Acceleration', unit: 'm/s²', description: 'Acceleration' },
      { symbol: 't', name: 'Time', unit: 's', description: 'Time' },
    ],
    explanation: 'Second equation of motion: displacement as a function of initial velocity, acceleration, and time.',
    explanation_beginner: 'How far you travel depends on how fast you start and how quickly you speed up.',
    explanation_advanced: 'Derived by integrating v = u + at: s = ∫v dt = ut + ½at².',
    relatedEquations: ['kinematic-v-u-at', 'kinematic-v2-u2'],
    simulationType: 'projectile',
    availableActions: ['explain', 'simulate', 'graph', 'practice'],
    jeeRelevance: 'JEE: Use when final velocity is not required.',
    prerequisites: ['kinematic-v-u-at'],
    tags: ['kinematics', 'displacement', 'equations-of-motion'],
  },
  {
    id: 'kinematic-v2-u2',
    latex: 'v^2 = u^2 + 2as',
    aliases: ['v2=u2+2as', 'v² = u² + 2as', 'third equation of motion', '3rd equation of motion'],
    displayName: '3rd Equation of Motion',
    subject: 'physics',
    topic: 'kinematics',
    variables: [
      { symbol: 'v', name: 'Final velocity', unit: 'm/s', description: 'Final velocity' },
      { symbol: 'u', name: 'Initial velocity', unit: 'm/s', description: 'Initial velocity' },
      { symbol: 'a', name: 'Acceleration', unit: 'm/s²', description: 'Acceleration' },
      { symbol: 's', name: 'Displacement', unit: 'm', description: 'Displacement' },
    ],
    explanation: 'Third equation of motion: relates velocities, acceleration, and displacement without time.',
    explanation_beginner: "Use this when you don't know or need the time.",
    explanation_advanced: 'Eliminates t from the first two equations: v² = u² + 2as.',
    relatedEquations: ['kinematic-v-u-at', 'kinematic-s-ut'],
    simulationType: 'projectile',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Most useful when time is not given or required.',
    prerequisites: ['kinematic-v-u-at'],
    tags: ['kinematics', 'equations-of-motion'],
  },
  {
    id: 'projectile-motion',
    latex: 'y = x\\tan\\theta - \\frac{gx^2}{2v_0^2\\cos^2\\theta}',
    aliases: ['projectile motion', 'projectile', 'trajectory', 'parabola motion', 'projectile arc'],
    displayName: 'Projectile Motion',
    subject: 'physics',
    topic: 'kinematics',
    variables: [
      { symbol: 'θ', name: 'Launch angle', unit: '°', defaultValue: 45 },
      { symbol: 'v₀', name: 'Launch speed', unit: 'm/s', defaultValue: 20 },
      { symbol: 'g', name: 'Gravity', unit: 'm/s²', defaultValue: 9.8 },
    ],
    explanation: 'Motion of an object thrown into the air under gravity in two dimensions.',
    explanation_beginner: 'Throwing a basketball — it follows a parabolic arc up and down.',
    explanation_advanced: 'Horizontal: x = (v₀ cosθ)t. Vertical: y = (v₀ sinθ)t - ½gt². Trajectory equation is quadratic in x.',
    relatedEquations: ['kinematic-v-u-at', 'kinematic-s-ut'],
    simulationType: 'projectile',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Range R = v₀² sin2θ / g, Max Height H = v₀² sin²θ / (2g), Flight Time T = 2v₀ sinθ / g.',
    prerequisites: ['kinematic-v-u-at'],
    tags: ['kinematics', 'projectile', 'motion'],
  },
  {
    id: 'kinetic-energy',
    latex: 'KE = \\frac{1}{2}mv^2',
    aliases: ['ke=½mv2', 'ke = 1/2 mv2', 'kinetic energy', '½mv²', '0.5mv2', 'ke=1/2mv^2', 'ke = 1/2 mv^2'],
    displayName: 'Kinetic Energy',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'KE', name: 'Kinetic Energy', unit: 'J', description: 'Energy of motion' },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Mass', min: 1, max: 100, defaultValue: 10 },
      { symbol: 'v', name: 'Velocity', unit: 'm/s', description: 'Speed of object', min: 0, max: 50, defaultValue: 12 },
    ],
    explanation: 'Kinetic energy is the energy possessed by an object due to its motion.',
    explanation_beginner: 'Fast things have more energy. Doubling speed gives 4× the energy!',
    explanation_advanced: 'KE = ½mv². Note the quadratic dependence on v — doubling velocity quadruples KE. Work-energy theorem: W_net = ΔKE.',
    relatedEquations: ['work', 'potential-energy-gravitational', 'conservation-energy'],
    simulationType: 'kinetic',
    graphType: 'cartesian',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz', 'example'],
    jeeRelevance: 'JEE: Work-energy theorem W = ΔKE. Power P = Fv. KE is always positive.',
    prerequisites: ['momentum'],
    tags: ['energy', 'mechanics', 'kinetic'],
  },
  {
    id: 'gravitational-pe',
    latex: 'PE = mgh',
    aliases: ['pe=mgh', 'potential energy', 'gravitational potential energy', 'mgh', 'pe = mgh'],
    displayName: 'Gravitational Potential Energy',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'PE', name: 'Potential Energy', unit: 'J', description: 'Stored energy due to height' },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Mass' },
      { symbol: 'g', name: 'Gravitational acceleration', unit: 'm/s²', defaultValue: 9.8 },
      { symbol: 'h', name: 'Height', unit: 'm', description: 'Height above reference' },
    ],
    explanation: 'Gravitational potential energy stored in an object at height h above a reference level.',
    explanation_beginner: 'The higher you lift something, the more energy you store in it — like a raised hammer.',
    explanation_advanced: "PE = mgh (valid near Earth's surface). At large distances: U = -GMm/r.",
    relatedEquations: ['kinetic-energy', 'conservation-energy', 'newton-gravitation'],
    simulationType: 'kinetic',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Conservation of mechanical energy: KE + PE = constant (no friction).',
    prerequisites: ['weight'],
    tags: ['energy', 'mechanics', 'gravity'],
  },
  {
    id: 'work',
    latex: 'W = Fd\\cos\\theta',
    aliases: ['w=fdcostheta', 'w = fd cos θ', 'work done', 'work = force * distance', 'w=fd', 'w = fd'],
    displayName: 'Work Done',
    subject: 'physics',
    topic: 'mechanics',
    variables: [
      { symbol: 'W', name: 'Work', unit: 'J', description: 'Work done by force' },
      { symbol: 'F', name: 'Force', unit: 'N', description: 'Applied force' },
      { symbol: 'd', name: 'Displacement', unit: 'm', description: 'Displacement' },
      { symbol: 'θ', name: 'Angle', unit: '°', description: 'Angle between force and displacement' },
    ],
    explanation: 'Work is done when a force causes displacement in the direction of the force.',
    explanation_beginner: 'Pushing a box across the floor — the harder you push and the farther it goes, the more work you do.',
    explanation_advanced: 'W = F·d·cosθ = F⃗·d⃗ (dot product). Work is zero if force is perpendicular to displacement.',
    relatedEquations: ['kinetic-energy', 'power', 'newton-second-law'],
    simulationType: 'newton',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: W = 0 for perpendicular force. Negative work when force opposes motion.',
    prerequisites: ['newton-second-law'],
    tags: ['work', 'energy', 'mechanics'],
  },

  // ── GRAVITATION ─────────────────────────────────────────
  {
    id: 'newton-gravitation',
    latex: 'F = \\frac{GMm}{r^2}',
    aliases: ['f=gmm/r2', 'f = gmm/r²', 'newton law of gravitation', 'gravitational force', 'universal gravitation', 'f=g*m*m/r^2', 'kepler', 'keplers law', 'kepler laws'],
    displayName: "Newton's Law of Gravitation",
    subject: 'physics',
    topic: 'gravitation',
    variables: [
      { symbol: 'F', name: 'Gravitational Force', unit: 'N', description: 'Attractive force' },
      { symbol: 'G', name: 'Gravitational Constant', unit: 'N·m²/kg²', description: 'G = 6.674×10⁻¹¹', defaultValue: 6.674e-11 },
      { symbol: 'M', name: 'Mass 1', unit: 'kg', description: 'First mass', min: 1e20, max: 1e25, defaultValue: 5.97e24 },
      { symbol: 'm', name: 'Mass 2', unit: 'kg', description: 'Second mass', min: 10, max: 1000, defaultValue: 500 },
      { symbol: 'r', name: 'Distance', unit: 'm', description: 'Distance between centres', min: 1e6, max: 1e8, defaultValue: 6.7e6 },
    ],
    explanation: 'Every mass attracts every other mass with a force proportional to their masses and inversely proportional to the square of distance.',
    explanation_beginner: 'The Sun pulls the Earth because both have mass. Bigger masses or closer distances = stronger pull.',
    explanation_advanced: "F = GMm/r² — inverse square law. G = 6.674×10⁻¹¹ N·m²/kg². Leads to orbital mechanics and Kepler's laws.",
    relatedEquations: ['orbital-velocity', 'escape-velocity', 'gravitational-field'],
    simulationType: 'gravitation',
    graphType: 'cartesian',
    availableActions: ['explain', 'visualize', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Escape velocity v_e = √(2GM/R). Orbital velocity v_o = √(GM/R).',
    prerequisites: ['newton-second-law', 'weight'],
    tags: ['gravitation', 'newton', 'inverse-square'],
  },
  {
    id: 'escape-velocity',
    latex: 'v_e = \\sqrt{\\frac{2GM}{R}}',
    aliases: ['escape velocity', 've=sqrt(2gm/r)', 'v_e', 'escape speed'],
    displayName: 'Escape Velocity',
    subject: 'physics',
    topic: 'gravitation',
    variables: [
      { symbol: 'v_e', name: 'Escape velocity', unit: 'm/s', description: 'Minimum escape speed' },
      { symbol: 'G', name: 'Gravitational constant', unit: 'N·m²/kg²', defaultValue: 6.674e-11 },
      { symbol: 'M', name: 'Mass of planet', unit: 'kg', description: 'Planet mass' },
      { symbol: 'R', name: 'Radius of planet', unit: 'm', description: 'Planet radius' },
    ],
    explanation: "Minimum speed needed to escape a planet's gravitational field without further propulsion.",
    explanation_beginner: "The speed a rocket needs to break free of Earth's gravity forever — about 11.2 km/s!",
    explanation_advanced: 'Derived by equating KE = gravitational PE: ½mv² = GMm/R → v_e = √(2GM/R). Note: independent of projectile mass.',
    relatedEquations: ['newton-gravitation', 'orbital-velocity'],
    simulationType: 'gravitation',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: v_e = √2 × v_orbital. Earth v_e ≈ 11.2 km/s.',
    prerequisites: ['newton-gravitation', 'kinetic-energy'],
    tags: ['gravitation', 'escape', 'orbital'],
  },
  {
    id: 'orbital-velocity',
    latex: 'v_o = \\sqrt{\\frac{GM}{r}}',
    aliases: ['orbital velocity', 'vo=sqrt(gm/r)', 'v_o', 'orbital speed'],
    displayName: 'Orbital Velocity',
    subject: 'physics',
    topic: 'gravitation',
    variables: [
      { symbol: 'v_o', name: 'Orbital velocity', unit: 'm/s', description: 'Circular orbital speed' },
      { symbol: 'G', name: 'Gravitational constant', unit: 'N·m²/kg²', defaultValue: 6.674e-11 },
      { symbol: 'M', name: 'Central mass', unit: 'kg', description: 'Planet/star mass' },
      { symbol: 'r', name: 'Orbital radius', unit: 'm', description: 'Distance from center' },
    ],
    explanation: 'Speed required for a satellite to stay in a stable circular orbit.',
    explanation_beginner: 'A satellite stays in space by continuously falling around the Earth at just the right speed.',
    explanation_advanced: 'Equating centripetal force and gravity: mv²/r = GMm/r² → v_o = √(GM/r). Period T = 2πr/v_o = 2π√(r³/GM).',
    relatedEquations: ['newton-gravitation', 'escape-velocity'],
    simulationType: 'gravitation',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Kepler\'s 3rd Law T² ∝ r³ derived from orbital velocity.',
    prerequisites: ['newton-gravitation'],
    tags: ['gravitation', 'orbit', 'satellite'],
  },

  // ── WAVES & OSCILLATIONS ───────────────────────────────
  {
    id: 'wave-speed',
    latex: 'v = f\\lambda',
    aliases: ['v=fl', 'v=fλ', 'wave speed', 'v = f lambda', 'v=f*lambda', 'standing waves', 'standing wave'],
    displayName: 'Wave Speed & Standing Waves',
    subject: 'physics',
    topic: 'waves',
    variables: [
      { symbol: 'v', name: 'Wave speed', unit: 'm/s', description: 'Speed of wave' },
      { symbol: 'f', name: 'Frequency', unit: 'Hz', description: 'Oscillations per second', min: 0.1, max: 10, defaultValue: 2 },
      { symbol: 'λ', name: 'Wavelength', unit: 'm', description: 'Distance per cycle' },
    ],
    explanation: 'Wave speed equals frequency times wavelength.',
    explanation_beginner: 'Waves with higher frequency have shorter wavelengths if the speed stays constant.',
    explanation_advanced: 'v = fλ holds for all transverse and longitudinal waves. For light in vacuum: c = 3×10⁸ m/s.',
    relatedEquations: ['shm-displacement', 'period-frequency'],
    simulationType: 'wave',
    graphType: 'cartesian',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Frequency set by source, speed by medium, wavelength changes with medium.',
    prerequisites: ['period-frequency'],
    tags: ['waves', 'frequency', 'wavelength'],
  },
  {
    id: 'shm-displacement',
    latex: 'x = A\\sin(\\omega t + \\phi)',
    aliases: ['x=asin', 'shm', 'simple harmonic motion', 'x = A sin(ωt)', 'x=a*sin(wt)', 'spring force', 'f=-kx', 'f = -kx', 'hooke law'],
    displayName: 'SHM & Spring Motion',
    subject: 'physics',
    topic: 'oscillations',
    variables: [
      { symbol: 'x', name: 'Displacement', unit: 'm', description: 'Position from equilibrium' },
      { symbol: 'A', name: 'Amplitude', unit: 'm', description: 'Maximum displacement', min: 0.1, max: 5, defaultValue: 1 },
      { symbol: 'ω', name: 'Angular frequency', unit: 'rad/s', description: 'ω = 2πf', min: 0.5, max: 10, defaultValue: 2 },
      { symbol: 't', name: 'Time', unit: 's', description: 'Time' },
      { symbol: 'φ', name: 'Phase', unit: 'rad', description: 'Initial phase', defaultValue: 0 },
    ],
    explanation: 'SHM displacement as a sinusoidal function of time.',
    explanation_beginner: 'A pendulum or spring bobs back and forth — its position follows a smooth wave pattern.',
    explanation_advanced: 'x = A sin(ωt + φ). Velocity: v = Aω cos(ωt + φ). Acceleration: a = -Aω² sin(ωt + φ) = -ω²x.',
    relatedEquations: ['wave-speed', 'pendulum-period'],
    simulationType: 'shm',
    graphType: 'cartesian',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: a = -ω²x is the defining condition for SHM. ω = √(k/m) for spring.',
    prerequisites: ['wave-speed'],
    tags: ['shm', 'oscillation', 'periodic'],
  },
  {
    id: 'pendulum-period',
    latex: 'T = 2\\pi\\sqrt{\\frac{L}{g}}',
    aliases: ['t=2pi*sqrt(l/g)', 'pendulum period', 't = 2π√(l/g)', 'simple pendulum', 'pendulum'],
    displayName: 'Simple Pendulum Period',
    subject: 'physics',
    topic: 'oscillations',
    variables: [
      { symbol: 'T', name: 'Period', unit: 's', description: 'Time for one full swing' },
      { symbol: 'L', name: 'Length', unit: 'm', description: 'Pendulum length', min: 0.2, max: 5, defaultValue: 1 },
      { symbol: 'g', name: 'Gravity', unit: 'm/s²', description: 'Gravitational acceleration', defaultValue: 9.8 },
    ],
    explanation: 'Period of a simple pendulum for small angles of oscillation.',
    explanation_beginner: 'Longer pendulums swing slower. Mass of the bob does not change the period!',
    explanation_advanced: 'T = 2π√(L/g). Valid for small angular amplitudes θ < 15°. Independent of mass m.',
    relatedEquations: ['shm-displacement'],
    simulationType: 'pendulum',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: T depends on L and g, independent of mass. In accelerating elevator: g_eff = g ± a.',
    prerequisites: ['shm-displacement'],
    tags: ['oscillations', 'pendulum', 'period'],
  },
  {
    id: 'double-slit',
    latex: 'y = \\frac{\\lambda D}{d}',
    aliases: ['y=lambda*d/d', 'double slit', 'interference fringe width', 'youngs double slit', 'wave interference', 'interference'],
    displayName: 'Wave Interference (Double Slit)',
    subject: 'physics',
    topic: 'optics',
    variables: [
      { symbol: 'β', name: 'Fringe width', unit: 'm', description: 'Distance between adjacent bright fringes' },
      { symbol: 'λ', name: 'Wavelength', unit: 'm', description: 'Light wavelength', min: 400e-9, max: 700e-9, defaultValue: 550e-9 },
      { symbol: 'D', name: 'Screen distance', unit: 'm', description: 'Distance from slits to screen', min: 0.5, max: 3, defaultValue: 1.5 },
      { symbol: 'd', name: 'Slit separation', unit: 'm', description: 'Distance between slits', min: 0.1e-3, max: 2e-3, defaultValue: 0.5e-3 },
    ],
    explanation: "Calculates fringe spacing β = λD/d in Young's double slit interference experiment.",
    explanation_beginner: 'Passing light through two tiny slits creates alternating bright and dark stripes on a screen.',
    explanation_advanced: 'Constructive interference: d sinθ = mλ. Destructive: d sinθ = (m + ½)λ. Fringe width β = λD/d.',
    relatedEquations: ['wave-speed'],
    simulationType: 'interference',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Shift in fringe pattern when thin film inserted: Δx = (μ-1)t D / d.',
    prerequisites: ['wave-speed'],
    tags: ['optics', 'waves', 'interference', 'youngs-double-slit'],
  },

  // ── ELECTRICITY & MAGNETISM ────────────────────────────
  {
    id: 'ohms-law',
    latex: 'V = IR',
    aliases: ['v=ir', 'ohm', 'ohms law', 'voltage = current * resistance', 'p=vi', 'p=i2r', 'p=v2/r'],
    displayName: "Ohm's Law & Circuit Power",
    subject: 'physics',
    topic: 'electricity',
    variables: [
      { symbol: 'V', name: 'Voltage', unit: 'V', description: 'Potential difference', min: 1, max: 30, defaultValue: 12 },
      { symbol: 'I', name: 'Current', unit: 'A', description: 'Electric current' },
      { symbol: 'R', name: 'Resistance', unit: 'Ω', description: 'Resistance', min: 1, max: 25, defaultValue: 4 },
    ],
    explanation: "Ohm's Law: voltage equals current times resistance.",
    explanation_beginner: 'Higher voltage pushes more current through the same resistance — like higher water pressure through a pipe.',
    explanation_advanced: "V = IR for ohmic conductors. Power: P = VI = I²R = V²/R. Kirchhoff's laws govern complex circuits.",
    relatedEquations: ['circuit-law'],
    simulationType: 'ohm',
    availableActions: ['explain', 'simulate', 'practice', 'quiz', 'example'],
    jeeRelevance: 'JEE: P = I²R = V²/R. Series: same I. Parallel: same V.',
    prerequisites: [],
    tags: ['electricity', 'ohm', 'circuit'],
  },
  {
    id: 'circuit-law',
    latex: '\\text{Circuit } V, I, R',
    aliases: ['circuit', 'electrical circuit', 'electric circuit', 'kirchhoff', 'kirchhoff law', 'series circuit', 'parallel circuit', 'q=cv', 'capacitance', 'capacitor'],
    displayName: 'Electrical Circuit',
    subject: 'physics',
    topic: 'electricity',
    variables: [
      { symbol: 'V', name: 'Voltage', unit: 'V', defaultValue: 12 },
      { symbol: 'I', name: 'Current', unit: 'A', defaultValue: 3 },
      { symbol: 'R', name: 'Resistance', unit: 'Ω', defaultValue: 4 },
    ],
    explanation: 'Direct current circuit analyzing current flow, voltage drops, and equivalent resistance.',
    explanation_beginner: 'Electrons flow from the positive to negative terminal of a battery through resistors.',
    explanation_advanced: 'KCL: ΣI_in = ΣI_out. KVL: ΣV = 0 around any closed loop.',
    relatedEquations: ['ohms-law'],
    simulationType: 'circuit',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Wheatstone bridge equilibrium condition R1/R2 = R3/R4.',
    prerequisites: ['ohms-law'],
    tags: ['electricity', 'circuit'],
  },
  {
    id: 'coulombs-law',
    latex: 'F = \\frac{kq_1q_2}{r^2}',
    aliases: ['coulomb', 'f=kq1q2/r2', 'coulombs law', 'electric force', 'electric field', 'e=f/q'],
    displayName: "Coulomb's Law & Electric Field",
    subject: 'physics',
    topic: 'electricity',
    variables: [
      { symbol: 'F', name: 'Electric force', unit: 'N', description: 'Force between charges' },
      { symbol: 'k', name: 'Coulomb constant', unit: 'N·m²/C²', description: 'k = 8.99×10⁹', defaultValue: 8.99e9 },
      { symbol: 'q₁', name: 'Charge 1', unit: 'C', description: 'First charge' },
      { symbol: 'q₂', name: 'Charge 2', unit: 'C', description: 'Second charge' },
      { symbol: 'r', name: 'Distance', unit: 'm', description: 'Distance between charges' },
    ],
    explanation: "Coulomb's Law gives the electrostatic force between two point charges.",
    explanation_beginner: 'Like charges repel, unlike charges attract — the force is stronger when they are closer.',
    explanation_advanced: 'F = kq₁q₂/r². Analogous to gravity but can be repulsive. k = 1/(4πε₀) = 8.99×10⁹ N·m²/C².',
    relatedEquations: ['lorentz-force'],
    simulationType: 'coulomb',
    availableActions: ['explain', 'visualize', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Compare with gravity. Superposition principle for multiple charges.',
    prerequisites: ['newton-gravitation'],
    tags: ['electricity', 'coulomb', 'charges', 'electrostatics'],
  },
  {
    id: 'lorentz-force',
    latex: 'F = qvB\\sin\\theta',
    aliases: ['f=qvb', 'lorentz force', 'magnetic force', 'f = qvb sin(theta)'],
    displayName: 'Lorentz Magnetic Force',
    subject: 'physics',
    topic: 'magnetism',
    variables: [
      { symbol: 'F', name: 'Magnetic Force', unit: 'N', description: 'Deflecting force' },
      { symbol: 'q', name: 'Charge', unit: 'C', description: 'Particle charge', defaultValue: 1.6e-19 },
      { symbol: 'v', name: 'Velocity', unit: 'm/s', description: 'Particle speed', min: 1e5, max: 1e7, defaultValue: 2e6 },
      { symbol: 'B', name: 'Magnetic Field', unit: 'T', description: 'Field strength', min: 0.1, max: 5, defaultValue: 1 },
      { symbol: 'θ', name: 'Angle', unit: '°', description: 'Angle between v and B', defaultValue: 90 },
    ],
    explanation: 'Force exerted on a moving charge in a magnetic field: F = q(v × B).',
    explanation_beginner: 'Magnetic fields bend the paths of moving charged particles into circles or spirals!',
    explanation_advanced: 'F = q(v × B). Radius of circular orbit r = mv/(qB). Cyclotron frequency f = qB/(2πm).',
    relatedEquations: ['coulombs-law'],
    simulationType: 'lorentz',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Right-hand rule for direction. Circular path when v ⊥ B, helical path when angle θ ≠ 90°.',
    prerequisites: ['coulombs-law'],
    tags: ['magnetism', 'lorentz', 'force', 'particles'],
  },

  // ── OPTICS ─────────────────────────────────────────────
  {
    id: 'lens-equation',
    latex: '\\frac{1}{f} = \\frac{1}{v} - \\frac{1}{u}',
    aliases: ['1/f=1/v-1/u', 'lens equation', 'lens formula', 'mirror formula', '1/f = 1/v - 1/u', 'mirror equation', 'magnification', 'm=v/u'],
    displayName: 'Lens & Optics Ray Tracer',
    subject: 'physics',
    topic: 'optics',
    variables: [
      { symbol: 'f', name: 'Focal length', unit: 'm', description: 'Focal length of lens', min: 0.05, max: 2, defaultValue: 0.2 },
      { symbol: 'v', name: 'Image distance', unit: 'm', description: 'Distance to image' },
      { symbol: 'u', name: 'Object distance', unit: 'm', description: 'Distance to object', min: 0.1, max: 3, defaultValue: 0.4 },
    ],
    explanation: 'Relates object distance, image distance, and focal length for lenses and mirrors.',
    explanation_beginner: 'Move an object closer to a magnifying glass — the image moves further away.',
    explanation_advanced: '1/f = 1/v - 1/u. Sign convention: real = positive for lens. Magnification m = v/u.',
    relatedEquations: ['snells-law'],
    simulationType: 'lens',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Use consistent sign convention. Power P = 1/f (in metres) measured in dioptres.',
    prerequisites: [],
    tags: ['optics', 'lens', 'mirror', 'refraction'],
  },
  {
    id: 'snells-law',
    latex: 'n_1\\sin\\theta_1 = n_2\\sin\\theta_2',
    aliases: ['snells law', 'snell law', 'n1 sin theta = n2 sin theta', 'refraction', 'total internal reflection', 'tir', 'snell'],
    displayName: "Snell's Law & Refraction",
    subject: 'physics',
    topic: 'optics',
    variables: [
      { symbol: 'n₁', name: 'Refractive index 1', unit: '', description: 'Medium 1 refractive index' },
      { symbol: 'θ₁', name: 'Angle of incidence', unit: '°', description: 'Angle in medium 1' },
      { symbol: 'n₂', name: 'Refractive index 2', unit: '', description: 'Medium 2 refractive index' },
      { symbol: 'θ₂', name: 'Angle of refraction', unit: '°', description: 'Angle in medium 2' },
    ],
    explanation: "Snell's Law describes how light bends when it passes between media of different refractive indices.",
    explanation_beginner: "Light bends when it moves from air into water — that's why a straw looks broken in a glass!",
    explanation_advanced: 'n₁sinθ₁ = n₂sinθ₂. Derived from Fermat\'s principle. Critical angle: sinθ_c = n₂/n₁.',
    relatedEquations: ['lens-equation'],
    simulationType: 'refraction',
    availableActions: ['explain', 'visualize', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Critical angle sinθ_c = 1/n for glass-air. TIR occurs beyond critical angle.',
    prerequisites: [],
    tags: ['optics', 'refraction', 'light', 'snell'],
  },

  // ── THERMODYNAMICS & FLUIDS ───────────────────────────
  {
    id: 'ideal-gas-law',
    latex: 'PV = nRT',
    aliases: ['pv=nrt', 'ideal gas', 'pv = nrt', 'gas law'],
    displayName: 'Ideal Gas Law',
    subject: 'physics',
    topic: 'thermodynamics',
    variables: [
      { symbol: 'P', name: 'Pressure', unit: 'Pa', description: 'Gas pressure', min: 1e4, max: 1e6, defaultValue: 1e5 },
      { symbol: 'V', name: 'Volume', unit: 'm³', description: 'Gas volume', min: 0.001, max: 1, defaultValue: 0.1 },
      { symbol: 'n', name: 'Moles', unit: 'mol', description: 'Amount of substance', defaultValue: 1 },
      { symbol: 'R', name: 'Gas constant', unit: 'J/(mol·K)', description: 'R = 8.314', defaultValue: 8.314 },
      { symbol: 'T', name: 'Temperature', unit: 'K', description: 'Absolute temperature', min: 10, max: 1000, defaultValue: 300 },
    ],
    explanation: 'The ideal gas law relates pressure, volume, temperature, and amount of an ideal gas.',
    explanation_beginner: 'Squeeze a balloon (smaller V) and the pressure increases. Heat it up and it expands.',
    explanation_advanced: 'PV = nRT. Derived from kinetic theory. Combined gas law: P₁V₁/T₁ = P₂V₂/T₂.',
    relatedEquations: ['specific-heat', 'thermodynamics-law'],
    simulationType: 'gas',
    graphType: 'cartesian',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: PV = nRT. Isothermal: PV=const. Isobaric: V/T=const. Isochoric: P/T=const.',
    prerequisites: [],
    tags: ['thermodynamics', 'gas', 'temperature', 'pressure'],
  },
  {
    id: 'specific-heat',
    latex: 'Q = mc\\Delta T',
    aliases: ['q=mcdeltat', 'q = mc∆t', 'q=mct', 'specific heat', 'heat equation', 'q=mcΔt', 'q = mcΔt'],
    displayName: 'Specific Heat Capacity',
    subject: 'physics',
    topic: 'thermodynamics',
    variables: [
      { symbol: 'Q', name: 'Heat', unit: 'J', description: 'Heat energy transferred' },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Mass of substance' },
      { symbol: 'c', name: 'Specific heat', unit: 'J/(kg·K)', description: 'Specific heat capacity' },
      { symbol: 'ΔT', name: 'Temperature change', unit: 'K', description: 'Change in temperature' },
    ],
    explanation: 'Heat required to raise temperature of a substance.',
    explanation_beginner: 'Sand heats up faster than water because water has a higher specific heat capacity.',
    explanation_advanced: 'Q = mcΔT. c for water = 4186 J/(kg·K). Calorimetry: heat lost = heat gained.',
    relatedEquations: ['ideal-gas-law'],
    simulationType: 'heat',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Calorimetry problems. c_water = 4200 J/(kg·K). Latent heat for phase changes.',
    prerequisites: [],
    tags: ['thermodynamics', 'heat', 'temperature', 'calorimetry'],
  },
  {
    id: 'thermodynamics-law',
    latex: '\\Delta U = Q - W',
    aliases: ['first law of thermodynamics', 'carnot efficiency', 'carnot engine', 'delta u = q - w', 'Δu=q-w', 'thermodynamics 1st law'],
    displayName: '1st Law of Thermodynamics & Carnot',
    subject: 'physics',
    topic: 'thermodynamics',
    variables: [
      { symbol: 'ΔU', name: 'Internal Energy Change', unit: 'J' },
      { symbol: 'Q', name: 'Heat Added', unit: 'J' },
      { symbol: 'W', name: 'Work Done by System', unit: 'J' },
    ],
    explanation: 'Conservation of energy for thermodynamic systems.',
    explanation_beginner: 'Energy put into a system as heat goes into doing work or increasing internal temperature.',
    explanation_advanced: 'ΔU = Q - W. For cyclic process ΔU = 0 → Q = W. Carnot max efficiency η = 1 - T_C/T_H.',
    relatedEquations: ['ideal-gas-law', 'specific-heat'],
    simulationType: 'thermodynamic',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Work in isothermal W = nRT ln(V2/V1). Adiabatic PV^γ = const.',
    prerequisites: ['ideal-gas-law'],
    tags: ['thermodynamics', 'carnot', 'heat'],
  },
  {
    id: 'bernoulli',
    latex: 'P + \\frac{1}{2}\\rho v^2 + \\rho gh = \\text{const}',
    aliases: ['bernoulli', 'p+1/2rhov2+rhogh', 'bernoullis principle', 'fluid dynamics', 'fluid'],
    displayName: "Bernoulli's Fluid Dynamics",
    subject: 'physics',
    topic: 'fluid-mechanics',
    variables: [
      { symbol: 'P', name: 'Static Pressure', unit: 'Pa', description: 'Fluid static pressure' },
      { symbol: 'ρ', name: 'Fluid Density', unit: 'kg/m³', description: 'Density of fluid', defaultValue: 1000 },
      { symbol: 'v', name: 'Flow Velocity', unit: 'm/s', description: 'Fluid speed', min: 0.5, max: 20, defaultValue: 2 },
      { symbol: 'h', name: 'Elevation', unit: 'm', description: 'Height above datum', defaultValue: 0 },
    ],
    explanation: "Bernoulli's principle: an increase in fluid speed occurs simultaneously with a decrease in static pressure.",
    explanation_beginner: 'Faster moving air has lower pressure — that is how airplane wings create lift!',
    explanation_advanced: 'P + ½ρv² + ρgh = constant along a streamline. Statement of conservation of energy for incompressible, non-viscous fluid.',
    relatedEquations: ['ideal-gas-law'],
    simulationType: 'fluid',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Venturimeter, Torricelli\'s law v = √(2gh), airplane lift force.',
    prerequisites: [],
    tags: ['fluids', 'bernoulli', 'pressure', 'hydrodynamics'],
  },

  // ── MODERN PHYSICS ─────────────────────────────────────
  {
    id: 'mass-energy',
    latex: 'E = mc^2',
    aliases: ['e=mc2', 'e = mc²', 'einstein', 'mass energy equivalence', 'e=m*c^2'],
    displayName: 'Mass-Energy Equivalence',
    subject: 'physics',
    topic: 'modern-physics',
    variables: [
      { symbol: 'E', name: 'Energy', unit: 'J', description: 'Rest energy' },
      { symbol: 'm', name: 'Mass', unit: 'kg', description: 'Rest mass' },
      { symbol: 'c', name: 'Speed of light', unit: 'm/s', description: 'c = 3×10⁸', defaultValue: 3e8 },
    ],
    explanation: "Einstein's mass-energy equivalence: mass and energy are interchangeable.",
    explanation_beginner: "A tiny amount of mass converts to an enormous amount of energy — that's the principle behind nuclear power.",
    explanation_advanced: 'E₀ = mc². Total energy E = γmc². 1g of mass → 9×10¹³ J ≈ 21 kilotons of TNT.',
    relatedEquations: ['photon-energy', 'radioactive-decay'],
    simulationType: 'einstein',
    availableActions: ['explain', 'visualize', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Nuclear binding energy calculations. Mass defect Δm → E = Δmc².',
    prerequisites: [],
    tags: ['modern-physics', 'relativity', 'einstein', 'nuclear'],
  },
  {
    id: 'photon-energy',
    latex: 'E = hf',
    aliases: ['e=hf', 'photon energy', 'planck', 'e = hν', 'e = hf', 'photoelectric effect'],
    displayName: 'Photon Energy & Photoelectric Effect',
    subject: 'physics',
    topic: 'modern-physics',
    variables: [
      { symbol: 'E', name: 'Photon energy', unit: 'J', description: 'Energy of one photon' },
      { symbol: 'h', name: "Planck's constant", unit: 'J·s', description: 'h = 6.626×10⁻³⁴', defaultValue: 6.626e-34 },
      { symbol: 'f', name: 'Frequency', unit: 'Hz', description: 'Frequency of light' },
    ],
    explanation: "Planck's quantum relation: energy of a photon is proportional to its frequency.",
    explanation_beginner: 'Violet light carries more energy than red light because it has higher frequency.',
    explanation_advanced: 'E = hf = hc/λ. Photoelectric effect: maximum KE = hf - φ (work function).',
    relatedEquations: ['mass-energy', 'wave-speed'],
    simulationType: 'photoelectric',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Photoelectric effect — threshold frequency, stopping potential, work function.',
    prerequisites: [],
    tags: ['quantum', 'photon', 'planck', 'modern-physics'],
  },
  {
    id: 'radioactive-decay',
    latex: 'N(t) = N_0 e^{-\\lambda t}',
    aliases: ['n=n0e^-lambdat', 'radioactive decay', 'half life', 'half-life', 'decay law'],
    displayName: 'Radioactive Decay & Half-Life',
    subject: 'physics',
    topic: 'modern-physics',
    variables: [
      { symbol: 'N', name: 'Remaining Nuclei', unit: '', description: 'Number of undecayed nuclei' },
      { symbol: 'N₀', name: 'Initial Nuclei', unit: '', description: 'Starting number', defaultValue: 1000 },
      { symbol: 'λ', name: 'Decay Constant', unit: 's⁻¹', description: 'Decay probability rate', defaultValue: 0.1 },
      { symbol: 't', name: 'Time', unit: 's', description: 'Time elapsed' },
    ],
    explanation: 'The number of radioactive nuclei decreases exponentially over time.',
    explanation_beginner: 'In each half-life, half of the remaining radioactive atoms decay away.',
    explanation_advanced: 'N(t) = N₀ e^(-λt). Half-life T₁/₂ = ln(2)/λ ≈ 0.693/λ. Activity A = -dN/dt = λN.',
    relatedEquations: ['mass-energy'],
    simulationType: 'decay',
    graphType: 'cartesian',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Half-life T₁/₂ = 0.693/λ. Mean life τ = 1/λ. Carbon dating applications.',
    prerequisites: [],
    tags: ['modern-physics', 'nuclear', 'decay', 'exponential'],
  },

  // ── MATHEMATICS — GRAPHING ──────────────────────────────
  {
    id: 'quadratic',
    latex: 'y = ax^2 + bx + c',
    aliases: ['y=ax2+bx+c', 'quadratic', 'parabola', 'y = ax² + bx + c', 'y=x^2', 'y=x²', 'quadratic equation', 'quadratic function', 'polynomial', 'parametric equations'],
    displayName: 'Quadratic & Function Grapher',
    subject: 'mathematics',
    topic: 'algebra',
    variables: [
      { symbol: 'a', name: 'Coefficient a', unit: '', description: 'Determines shape and opening', defaultValue: 1, min: -5, max: 5 },
      { symbol: 'b', name: 'Coefficient b', unit: '', description: 'Affects position of vertex', defaultValue: 0, min: -10, max: 10 },
      { symbol: 'c', name: 'Coefficient c', unit: '', description: 'y-intercept', defaultValue: 0, min: -10, max: 10 },
    ],
    explanation: 'A quadratic function produces a parabola. The vertex, roots, and axis of symmetry are key features.',
    explanation_beginner: 'The U-shaped curve. If a>0 it opens up, if a<0 it opens down.',
    explanation_advanced: 'Vertex: x = -b/2a. Discriminant Δ = b²-4ac determines number of roots. Roots: x = (-b ± √Δ)/2a.',
    relatedEquations: ['linear-function', 'circle-equation'],
    graphType: 'cartesian',
    simulationType: 'graph',
    availableActions: ['explain', 'graph', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Sum of roots = -b/a. Product = c/a. Discriminant rules for nature of roots.',
    prerequisites: [],
    tags: ['algebra', 'quadratic', 'parabola', 'graph'],
  },
  {
    id: 'linear-function',
    latex: 'y = mx + c',
    aliases: ['y=mx+c', 'linear', 'straight line', 'y = mx + b', 'slope intercept', 'y=2x+3'],
    displayName: 'Linear Function',
    subject: 'mathematics',
    topic: 'algebra',
    variables: [
      { symbol: 'm', name: 'Slope', unit: '', description: 'Rate of change', defaultValue: 1, min: -10, max: 10 },
      { symbol: 'c', name: 'Y-intercept', unit: '', description: 'Value when x=0', defaultValue: 0, min: -10, max: 10 },
    ],
    explanation: 'A linear function produces a straight line. m is the slope, c is the y-intercept.',
    explanation_beginner: 'A straight line graph. Steeper slope = larger m value.',
    explanation_advanced: 'Slope m = (y₂-y₁)/(x₂-x₁). Parallel lines have equal slopes. Perpendicular: m₁×m₂ = -1.',
    relatedEquations: ['quadratic', 'circle-equation'],
    graphType: 'cartesian',
    simulationType: 'graph',
    availableActions: ['explain', 'graph', 'simulate', 'practice'],
    jeeRelevance: 'JEE: Slope of tangent to curve = derivative at that point.',
    prerequisites: [],
    tags: ['algebra', 'linear', 'line', 'graph'],
  },
  {
    id: 'circle-equation',
    latex: 'x^2 + y^2 = r^2',
    aliases: ['x2+y2=r2', 'x² + y² = r²', 'circle equation', 'equation of circle', 'x^2+y^2=9'],
    displayName: 'Circle Equation',
    subject: 'mathematics',
    topic: 'coordinate-geometry',
    variables: [
      { symbol: 'r', name: 'Radius', unit: '', description: 'Radius of circle', defaultValue: 3, min: 0.5, max: 10 },
    ],
    explanation: 'Standard equation of a circle centered at the origin with radius r.',
    explanation_beginner: 'All points on a circle are the same distance from the centre — that distance is the radius.',
    explanation_advanced: 'x² + y² = r². General form: (x-h)² + (y-k)² = r² for centre (h,k). Area = πr², Circumference = 2πr.',
    relatedEquations: ['circle-area', 'quadratic'],
    graphType: 'cartesian',
    simulationType: 'graph',
    availableActions: ['explain', 'graph', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Tangent to circle x²+y²=r² at (x₁,y₁): xx₁+yy₁=r².',
    prerequisites: [],
    tags: ['geometry', 'circle', 'coordinate'],
  },
  {
    id: 'circle-area',
    latex: 'A = \\pi r^2',
    aliases: ['a=pir2', 'a = πr²', 'area of circle', 'circle area'],
    displayName: 'Circle Area',
    subject: 'mathematics',
    topic: 'geometry',
    variables: [
      { symbol: 'A', name: 'Area', unit: 'units²', description: 'Area enclosed by circle' },
      { symbol: 'π', name: 'Pi', unit: '', description: 'π ≈ 3.14159', defaultValue: Math.PI },
      { symbol: 'r', name: 'Radius', unit: 'units', description: 'Radius', min: 0.5, max: 10, defaultValue: 3 },
    ],
    explanation: 'Area of a circle as a function of radius.',
    explanation_beginner: 'Double the radius and the area becomes 4 times as big — because area depends on r².',
    explanation_advanced: 'A = πr². dA/dr = 2πr (circumference). Area of sector = (θ/2π)×πr² = θr²/2.',
    relatedEquations: ['circle-equation'],
    graphType: 'cartesian',
    simulationType: 'circle-area',
    availableActions: ['explain', 'graph', 'simulate', 'practice'],
    jeeRelevance: 'JEE: Know all circle properties — tangent, chord, sector, segment.',
    prerequisites: [],
    tags: ['geometry', 'circle', 'area'],
  },
  {
    id: 'sine-function',
    latex: 'y = \\sin(x)',
    aliases: ['y=sinx', 'sin function', 'sine graph', 'y = sin(x)', 'trigonometry', 'y=cos(x)', 'y=tan(x)', 'y=e^x', 'y=log(x)', 'y=|x|', 'y=1/x', 'y=x^3-3x'],
    displayName: 'Trigonometric & Function Grapher',
    subject: 'mathematics',
    topic: 'trigonometry',
    variables: [
      { symbol: 'A', name: 'Amplitude', unit: '', description: 'Peak value', defaultValue: 1, min: 0.1, max: 5 },
      { symbol: 'ω', name: 'Angular frequency', unit: 'rad', description: 'Controls period', defaultValue: 1, min: 0.1, max: 5 },
      { symbol: 'φ', name: 'Phase shift', unit: 'rad', description: 'Horizontal shift', defaultValue: 0, min: -Math.PI, max: Math.PI },
    ],
    explanation: 'The sine function — fundamental in trigonometry, waves, and oscillations.',
    explanation_beginner: 'The sine wave is the shape of a smooth, repeating oscillation — like sound waves or pendulum motion.',
    explanation_advanced: 'y = A sin(ωx + φ). Period T = 2π/ω. Range [-A, A]. sin²x + cos²x = 1.',
    relatedEquations: ['shm-displacement', 'wave-speed'],
    graphType: 'cartesian',
    simulationType: 'graph',
    availableActions: ['explain', 'graph', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: sin²θ + cos²θ = 1. Values at 0,30,45,60,90° must be memorized.',
    prerequisites: [],
    tags: ['trigonometry', 'sine', 'wave', 'periodic'],
  },
  {
    id: 'sphere-volume',
    latex: 'V = \\frac{4}{3}\\pi r^3',
    aliases: ['sphere', 'sphere volume', 'v=4/3pir3', 'v = 4/3 pi r^3', 'cylinder', 'cone', '3d shape'],
    displayName: '3D Geometry Engine',
    subject: 'mathematics',
    topic: 'geometry',
    variables: [
      { symbol: 'r', name: 'Radius', unit: 'px', defaultValue: 60 },
      { symbol: 'h', name: 'Height', unit: 'px', defaultValue: 100 },
    ],
    explanation: 'Volume and surface area equations for 3D spheres, cylinders, and cones.',
    explanation_beginner: '3D volume measures space enclosed by a sphere or cylinder.',
    explanation_advanced: 'V_sphere = (4/3)πr³, V_cylinder = πr²h, V_cone = (1/3)πr²h.',
    relatedEquations: ['circle-area'],
    simulationType: 'geometry3d',
    availableActions: ['explain', 'simulate', 'graph', 'practice', 'quiz'],
    jeeRelevance: 'JEE: 3D mensuration & calculus volume integration.',
    prerequisites: ['circle-area'],
    tags: ['3d', 'sphere', 'cylinder', 'cone', 'geometry'],
  },
  {
    id: 'chemistry-engine',
    latex: '2H_2 + O_2 \\rightarrow 2H_2O',
    aliases: ['h2o', 'co2', 'ch4', 'nh3', 'chemistry', 'lewis', 'molecule', 'chemical reaction', 'reaction', 'valence'],
    displayName: 'Chemistry & 3D Molecular Engine',
    subject: 'chemistry',
    topic: 'modern-physics',
    variables: [],
    explanation: '3D molecular geometry, Lewis structures, and chemical reaction balancer.',
    explanation_beginner: 'Molecules form by sharing valence electron pairs.',
    explanation_advanced: 'VSEPR geometry determines 3D bond angles (Bent 104.5°, Linear 180°, Tetrahedral 109.5°).',
    relatedEquations: ['chemistry-engine'],
    simulationType: 'chemistry',
    availableActions: ['explain', 'simulate', 'practice', 'quiz'],
    jeeRelevance: 'JEE: Chemical bonding, VSEPR theory, and stoichiometry.',
    prerequisites: [],
    tags: ['chemistry', 'molecule', 'lewis', 'reaction'],
  },
];

// Detection function — searches registry
export function detectEquation(
  rawInput: string,
  activeSubject?: Subject
): { entry: EquationEntry | null; confidence: number } {
  if (!rawInput || !rawInput.trim()) return { entry: null, confidence: 0 };

  const rawLower = rawInput.toLowerCase().trim();

  // Normalize input string
  const normalized = rawLower
    .replace(/\s+/g, '')
    .replace(/\\left|\\right|\\cdot|\\times/g, '')
    .replace(/×/g, '*')
    .replace(/÷/g, '/')
    .replace(/²/g, '2')
    .replace(/³/g, '3')
    .replace(/¹/g, '1')
    .replace(/½/g, '1/2')
    .replace(/\\frac\{1\}\{2\}/g, '1/2')
    .replace(/\^2/g, '2')
    .replace(/\^3/g, '3')
    .replace(/λ/g, 'lambda')
    .replace(/ω/g, 'omega')
    .replace(/θ/g, 'theta')
    .replace(/π/g, 'pi')
    .replace(/Δ/g, 'delta')
    .replace(/τ/g, 'tau');

  // Filter list prioritized by activeSubject if provided
  const candidateRegistry = activeSubject
    ? [...equationRegistry.filter((e) => e.subject === activeSubject), ...equationRegistry.filter((e) => e.subject !== activeSubject)]
    : equationRegistry;

  for (const entry of candidateRegistry) {
    for (const alias of entry.aliases) {
      const normalizedAlias = alias
        .toLowerCase()
        .replace(/\s+/g, '')
        .replace(/²/g, '2')
        .replace(/³/g, '3')
        .replace(/½/g, '1/2')
        .replace(/\^2/g, '2')
        .replace(/\^3/g, '3')
        .replace(/λ/g, 'lambda')
        .replace(/ω/g, 'omega')
        .replace(/θ/g, 'theta')
        .replace(/π/g, 'pi')
        .replace(/Δ/g, 'delta')
        .replace(/τ/g, 'tau');

      if (
        normalized === normalizedAlias ||
        normalized.includes(normalizedAlias) ||
        normalizedAlias.includes(normalized) ||
        rawLower.includes(alias.toLowerCase())
      ) {
        return { entry, confidence: 0.95 };
      }
    }
  }

  // Fuzzy match on display names
  for (const entry of equationRegistry) {
    const nameNorm = entry.displayName.toLowerCase().replace(/\s+/g, '');
    if (normalized.includes(nameNorm) || nameNorm.includes(normalized) || rawLower.includes(entry.displayName.toLowerCase())) {
      return { entry, confidence: 0.78 };
    }
  }

  return { entry: null, confidence: 0 };
}

export function getEquationById(id: string): EquationEntry | undefined {
  return equationRegistry.find((e) => e.id === id);
}

export function getEquationsByTopic(topic: Topic): EquationEntry[] {
  return equationRegistry.filter((e) => e.topic === topic);
}

export function getEquationsBySubject(subject: Subject): EquationEntry[] {
  return equationRegistry.filter((e) => e.subject === subject);
}
