import type { SimulationType, SimulationEntry, Subject } from './types';

export const simulationMetadata: Partial<Record<SimulationType, SimulationEntry>> = {
  projectile: {
    id: 'projectile',
    subject: 'physics',
    category: 'Mechanics',
    name: 'Projectile Motion Physics',
    formula: 'y = x tan θ - (g x²) / (2 v₀² cos² θ)',
    description: 'Trajectory arc, velocity vectors vx & vy, max height, range, flight time.',
    parameters: [
      { symbol: 'θ', name: 'Launch Angle', unit: '°', defaultValue: 45, min: 5, max: 85 },
      { symbol: 'v₀', name: 'Initial Velocity', unit: 'm/s', defaultValue: 20, min: 2, max: 40 },
      { symbol: 'g', name: 'Gravity', unit: 'm/s²', defaultValue: 9.8, min: 1, max: 25 },
    ],
    equations: ['kinematic-v-u-at', 'kinematic-s-ut', 'kinematic-v2-u2'],
    component: 'ProjectileSim',
    keywords: ['projectile', 'motion', 'gravity', 'velocity', 'trajectory', 'angle', 'height', 'range'],
  },
  newton: {
    id: 'newton',
    subject: 'physics',
    category: 'Mechanics',
    name: "Newton's Second Law",
    formula: 'F = ma',
    description: 'Interactive mass on surface with dynamic force vector arrow scaling in real-time.',
    parameters: [
      { symbol: 'm', name: 'Mass', unit: 'kg', defaultValue: 8, min: 1, max: 25 },
      { symbol: 'a', name: 'Acceleration', unit: 'm/s²', defaultValue: 3, min: 0.5, max: 20 },
    ],
    equations: ['newton-second-law', 'weight', 'work'],
    component: 'NewtonSim',
    keywords: ['force', 'mass', 'acceleration', 'newton', 'motion', 'mechanics', 'vector'],
  },
  kinetic: {
    id: 'kinetic',
    subject: 'physics',
    category: 'Mechanics',
    name: 'Kinetic Energy Engine',
    formula: 'KE = ½mv²',
    description: 'Vehicle/object velocity vs mass comparison showing v² quadratic energy scaling.',
    parameters: [
      { symbol: 'm', name: 'Mass', unit: 'kg', defaultValue: 10, min: 1, max: 100 },
      { symbol: 'v', name: 'Velocity', unit: 'm/s', defaultValue: 12, min: 0, max: 50 },
    ],
    equations: ['kinetic-energy'],
    component: 'KineticSim',
    keywords: ['energy', 'kinetic', 'mass', 'velocity', 'work', 'power', 'speed'],
  },
  gravitation: {
    id: 'gravitation',
    subject: 'physics',
    category: 'Mechanics',
    name: 'Gravitational Force & Orbit',
    formula: 'F = G M m / r²',
    description: 'Two planetary masses with inverse-square force vector scaling and circular orbital motion.',
    parameters: [
      { symbol: 'M', name: 'Mass 1 (Planet)', unit: '×10²⁴ kg', defaultValue: 5.97, min: 0.1, max: 20 },
      { symbol: 'm', name: 'Mass 2 (Satellite)', unit: 'kg', defaultValue: 500, min: 10, max: 5000 },
      { symbol: 'r', name: 'Distance', unit: '1000 km', defaultValue: 6.7, min: 1, max: 30 },
    ],
    equations: ['newton-gravitation', 'escape-velocity'],
    component: 'GravitationSim',
    keywords: ['gravity', 'orbit', 'planet', 'kepler', 'satellite', 'gravitational', 'mass', 'distance'],
  },
  wave: {
    id: 'wave',
    subject: 'physics',
    category: 'Waves & Oscillations',
    name: 'Wave Speed Dynamics',
    formula: 'v = fλ',
    description: 'Animated transverse sine wave with amplitude, frequency, and wavelength markers.',
    parameters: [
      { symbol: 'A', name: 'Amplitude', unit: 'px', defaultValue: 40, min: 10, max: 90 },
      { symbol: 'f', name: 'Frequency', unit: 'Hz', defaultValue: 1.5, min: 0.5, max: 4 },
    ],
    equations: ['wave-speed'],
    component: 'WaveSim',
    keywords: ['wave', 'frequency', 'wavelength', 'speed', 'amplitude', 'sine', 'transverse'],
  },
  shm: {
    id: 'shm',
    subject: 'physics',
    category: 'Waves & Oscillations',
    name: 'Simple Harmonic Motion',
    formula: 'x = A sin(ωt)',
    description: 'Spring-mass oscillator alongside real-time scrolling displacement-time graph.',
    parameters: [
      { symbol: 'A', name: 'Amplitude', unit: 'px', defaultValue: 60, min: 20, max: 100 },
      { symbol: 'f', name: 'Frequency', unit: 'Hz', defaultValue: 1.2, min: 0.5, max: 3 },
      { symbol: 'm', name: 'Mass', unit: 'kg', defaultValue: 2, min: 1, max: 10 },
    ],
    equations: ['shm-displacement'],
    component: 'SHMSim',
    keywords: ['shm', 'oscillation', 'spring', 'harmonic', 'amplitude', 'period', 'frequency'],
  },
  pendulum: {
    id: 'pendulum',
    subject: 'physics',
    category: 'Waves & Oscillations',
    name: 'Simple Pendulum Physics',
    formula: 'T = 2π √(L / g)',
    description: 'Oscillating pendulum bob with period readout, displacement graph, and KE/PE energy bars.',
    parameters: [
      { symbol: 'L', name: 'Length', unit: 'm', defaultValue: 1.5, min: 0.3, max: 5 },
      { symbol: 'g', name: 'Gravity', unit: 'm/s²', defaultValue: 9.8, min: 1, max: 25 },
      { symbol: 'θ₀', name: 'Initial Angle', unit: '°', defaultValue: 20, min: 5, max: 45 },
    ],
    equations: ['pendulum-period', 'shm-displacement'],
    component: 'PendulumSim',
    keywords: ['pendulum', 'period', 'length', 'gravity', 'oscillation', 'time'],
  },
  interference: {
    id: 'interference',
    subject: 'physics',
    category: 'Waves & Oscillations',
    name: "Young's Double Slit Interference",
    formula: 'y = λ D / d',
    description: '2D ripple tank wave interference pattern showing constructive bright and destructive dark fringes.',
    parameters: [
      { symbol: 'λ', name: 'Wavelength', unit: 'nm', defaultValue: 550, min: 400, max: 700 },
      { symbol: 'd', name: 'Slit Separation', unit: 'mm', defaultValue: 0.5, min: 0.1, max: 2 },
      { symbol: 'D', name: 'Screen Distance', unit: 'm', defaultValue: 1.5, min: 0.5, max: 3 },
    ],
    equations: ['double-slit', 'wave-speed'],
    component: 'InterferenceSim',
    keywords: ['interference', 'double slit', 'young', 'fringe', 'light', 'diffraction', 'wave'],
  },
  ohm: {
    id: 'ohm',
    subject: 'physics',
    category: 'Electricity & Magnetism',
    name: "Ohm's Law Circuit",
    formula: 'V = I R',
    description: 'Schematic electrical circuit with animated flowing electrons proportional to current.',
    parameters: [
      { symbol: 'V', name: 'Voltage', unit: 'V', defaultValue: 12, min: 1, max: 30 },
      { symbol: 'R', name: 'Resistance', unit: 'Ω', defaultValue: 4, min: 1, max: 25 },
    ],
    equations: ['ohms-law', 'electric-power'],
    component: 'OhmSim',
    keywords: ['ohm', 'voltage', 'current', 'resistance', 'circuit', 'electricity', 'power'],
  },
  circuit: {
    id: 'circuit',
    subject: 'physics',
    category: 'Electricity & Magnetism',
    name: 'Multi-Resistor Circuit (Kirchhoff)',
    formula: 'ΣV = 0, ΣI = 0',
    description: 'Interactive circuit with series/parallel toggle, electron flow, and individual resistor V, I, P.',
    parameters: [
      { symbol: 'V', name: 'Source Voltage', unit: 'V', defaultValue: 12, min: 1, max: 40 },
      { symbol: 'R1', name: 'Resistor 1', unit: 'Ω', defaultValue: 4, min: 1, max: 30 },
      { symbol: 'R2', name: 'Resistor 2', unit: 'Ω', defaultValue: 6, min: 1, max: 30 },
      { symbol: 'R3', name: 'Resistor 3', unit: 'Ω', defaultValue: 12, min: 1, max: 30 },
    ],
    equations: ['ohms-law', 'electric-power'],
    component: 'CircuitSim',
    keywords: ['circuit', 'kirchhoff', 'resistor', 'series', 'parallel', 'current', 'voltage'],
  },
  lorentz: {
    id: 'lorentz',
    subject: 'physics',
    category: 'Electricity & Magnetism',
    name: 'Lorentz Magnetic Deflection',
    formula: 'F = q v B sin θ',
    description: 'Charged particle trajectory curving in magnetic field with circular orbit radius r = mv/qB.',
    parameters: [
      { symbol: 'v', name: 'Particle Speed', unit: '×10⁶ m/s', defaultValue: 2.5, min: 0.5, max: 10 },
      { symbol: 'B', name: 'Magnetic Field', unit: 'T', defaultValue: 1.2, min: 0.1, max: 5 },
      { symbol: 'q', name: 'Charge Sign', unit: '', defaultValue: 1, min: -1, max: 1 },
    ],
    equations: ['lorentz-force'],
    component: 'LorentzSim',
    keywords: ['lorentz', 'magnetic', 'field', 'charge', 'force', 'deflection', 'cyclotron'],
  },
  lens: {
    id: 'lens',
    subject: 'physics',
    category: 'Optics',
    name: 'Optics & Lens Ray Tracer',
    formula: '1/f = 1/v - 1/u',
    description: 'Convex/concave lens optics diagram with 3 principal rays, object drag, and image readout.',
    parameters: [
      { symbol: 'f', name: 'Focal Length', unit: 'cm', defaultValue: 15, min: 5, max: 40 },
      { symbol: 'u', name: 'Object Distance', unit: 'cm', defaultValue: 30, min: 5, max: 80 },
      { symbol: 'h', name: 'Object Height', unit: 'cm', defaultValue: 10, min: 2, max: 25 },
    ],
    equations: ['lens-equation', 'snells-law'],
    component: 'LensSim',
    keywords: ['lens', 'optics', 'focal', 'ray', 'convex', 'concave', 'refraction', 'image'],
  },
  gas: {
    id: 'gas',
    subject: 'physics',
    category: 'Thermodynamics',
    name: 'Ideal Gas Piston Engine',
    formula: 'P V = n R T',
    description: 'Animated gas particles in container with temperature speed scaling and live P-V graph.',
    parameters: [
      { symbol: 'T', name: 'Temperature', unit: 'K', defaultValue: 300, min: 50, max: 800 },
      { symbol: 'V', name: 'Volume (Piston)', unit: 'L', defaultValue: 5, min: 1, max: 15 },
      { symbol: 'n', name: 'Moles', unit: 'mol', defaultValue: 1, min: 0.2, max: 5 },
    ],
    equations: ['ideal-gas-law'],
    component: 'GasSim',
    keywords: ['gas', 'pressure', 'volume', 'temperature', 'piston', 'ideal gas', 'thermodynamics'],
  },
  thermodynamic: {
    id: 'thermodynamic',
    subject: 'physics',
    category: 'Thermodynamics',
    name: 'Heat Capacity Engine',
    formula: 'Q = m c ΔT',
    description: 'Calorimetry thermal exchange and P-V cycle heating/expansion.',
    parameters: [
      { symbol: 'm', name: 'Mass', unit: 'kg', defaultValue: 2, min: 0.5, max: 20 },
      { symbol: 'c', name: 'Specific Heat', unit: 'J/(kg·K)', defaultValue: 4186, min: 500, max: 5000 },
      { symbol: 'ΔT', name: 'Temperature Δ', unit: 'K', defaultValue: 25, min: 1, max: 100 },
    ],
    equations: ['specific-heat', 'ideal-gas-law'],
    component: 'ThermodynamicSim',
    keywords: ['heat', 'temperature', 'calorimetry', 'thermodynamics', 'expansion', 'specific heat'],
  },
  fluid: {
    id: 'fluid',
    subject: 'physics',
    category: 'Thermodynamics',
    name: 'Bernoulli Fluid Dynamics',
    formula: 'P + ½ρv² + ρgh = const',
    description: 'Constricted fluid pipe showing velocity acceleration and pressure drop.',
    parameters: [
      { symbol: 'v1', name: 'Inlet Velocity', unit: 'm/s', defaultValue: 2, min: 0.5, max: 10 },
      { symbol: 'A1/A2', name: 'Constriction Ratio', unit: '', defaultValue: 3, min: 1.2, max: 6 },
      { symbol: 'ρ', name: 'Fluid Density', unit: 'kg/m³', defaultValue: 1000, min: 500, max: 2000 },
    ],
    equations: ['bernoulli'],
    component: 'FluidSim',
    keywords: ['fluid', 'bernoulli', 'pipe', 'pressure', 'velocity', 'density', 'flow'],
  },
  photoelectric: {
    id: 'photoelectric',
    subject: 'physics',
    category: 'Modern Physics',
    name: 'Photoelectric Quantum Effect',
    formula: 'E = h f = Φ + KE_max',
    description: 'Monochromatic light beam ejecting photoelectrons from metal plate with stopping potential.',
    parameters: [
      { symbol: 'f', name: 'Light Frequency', unit: '×10¹⁴ Hz', defaultValue: 7.5, min: 3, max: 15 },
      { symbol: 'Φ', name: 'Work Function', unit: 'eV', defaultValue: 2.3, min: 1, max: 6 },
      { symbol: 'I', name: 'Light Intensity', unit: '%', defaultValue: 80, min: 10, max: 100 },
    ],
    equations: ['photon-energy', 'mass-energy'],
    component: 'PhotoelectricSim',
    keywords: ['photoelectric', 'photon', 'quantum', 'electron', 'work function', 'frequency', 'light'],
  },
  decay: {
    id: 'decay',
    subject: 'physics',
    category: 'Modern Physics',
    name: 'Radioactive Exponential Decay',
    formula: 'N = N₀ e^(-λt)',
    description: 'Nuclear decay simulation showing half-life probability decay curve.',
    parameters: [
      { symbol: 'N₀', name: 'Initial Nuclei', unit: '', defaultValue: 1000, min: 100, max: 5000 },
      { symbol: 't½', name: 'Half-Life', unit: 's', defaultValue: 5, min: 1, max: 20 },
    ],
    equations: ['radioactive-decay'],
    component: 'DecaySim',
    keywords: ['decay', 'radioactive', 'half life', 'nuclear', 'exponential', 'isotopes'],
  },
  chemistry: {
    id: 'chemistry',
    subject: 'chemistry',
    category: 'Molecules & Structure',
    name: '3D Molecular Structure Engine',
    formula: 'VSEPR Valence Geometry',
    description: 'Rotatable 3D molecular ball-and-stick bonds, Lewis valence structures, and chemical equation balancer.',
    parameters: [],
    equations: ['chemical-balancer', 'lewis-structure'],
    component: 'ChemistrySim',
    keywords: ['molecule', '3d', 'vsepr', 'bonding', 'lewis', 'structure', 'atom', 'valence'],
  },
  titration: {
    id: 'titration',
    subject: 'chemistry',
    category: 'Acids & Bases',
    name: 'Acid-Base Titration Laboratory',
    formula: 'M₁ V₁ = M₂ V₂ · pH = -log[H⁺]',
    description: 'Interactive burette, phenolphthalein indicator, digital pH meter, and live pH titration curve plot.',
    parameters: [
      { symbol: 'V_added', name: 'Volume Titrant', unit: 'mL', defaultValue: 0, min: 0, max: 50 },
      { symbol: 'C_acid', name: 'HCl Concentration', unit: 'M', defaultValue: 0.1, min: 0.05, max: 0.5 },
      { symbol: 'C_base', name: 'NaOH Concentration', unit: 'M', defaultValue: 0.1, min: 0.05, max: 0.5 },
    ],
    equations: ['ph-equation', 'molarity-dilution'],
    component: 'TitrationSim',
    keywords: ['titration', 'acid', 'base', 'ph', 'burette', 'indicator', 'equivalence', 'molarity'],
  },
  'water-lab': {
    id: 'water-lab',
    subject: 'chemistry',
    category: 'Water Laboratory',
    name: 'Dedicated Water (H₂O) Laboratory',
    formula: '2 H₂O ⟶ 2 H₂ + O₂',
    description: '3D dipole polarity, hydrogen bonding network, ice density anomaly, and water electrolysis.',
    parameters: [],
    equations: ['water-polarity', 'electrolysis'],
    component: 'WaterLabSim',
    keywords: ['water', 'h2o', 'polarity', 'hydrogen bonding', 'electrolysis', 'density', 'ice'],
  },
  kinetics: {
    id: 'kinetics',
    subject: 'chemistry',
    category: 'Chemical Kinetics',
    name: 'Kinetics & Energy Profile Engine',
    formula: 'k = A e^(-E_a / RT)',
    description: 'Reaction rate, Arrhenius rate constant, activation energy, catalyst effects, and energy coordinate diagrams.',
    parameters: [],
    equations: ['arrhenius-equation', 'rate-law'],
    component: 'KineticsSim',
    keywords: ['kinetics', 'arrhenius', 'activation energy', 'catalyst', 'rate constant', 'energy profile'],
  },
  equilibrium: {
    id: 'equilibrium',
    subject: 'chemistry',
    category: 'Chemical Equilibrium',
    name: 'Le Chatelier Equilibrium Engine',
    formula: 'N₂ + 3H₂ ⇌ 2NH₃ · K_c',
    description: 'Dynamic forward and reverse reaction kinetics with Le Chatelier temperature and concentration shifts.',
    parameters: [],
    equations: ['equilibrium-kc', 'le-chatelier'],
    component: 'EquilibriumSim',
    keywords: ['equilibrium', 'le chatelier', 'haber process', 'ammonia', 'kc', 'reversible'],
  },
  electrochemistry: {
    id: 'electrochemistry',
    subject: 'chemistry',
    category: 'Electrochemistry',
    name: 'Galvanic Cell & Nernst Equation',
    formula: 'E_cell = E° - (0.0592/n) log Q',
    description: 'Galvanic cell apparatus with Zn/Cu electrodes, salt bridge, electron flow, and Nernst voltage readout.',
    parameters: [],
    equations: ['nernst-equation', 'faraday-law'],
    component: 'ElectrochemistrySim',
    keywords: ['electrochemistry', 'galvanic cell', 'nernst', 'anode', 'cathode', 'salt bridge', 'voltage'],
  },
  'circle-area': {
    id: 'circle-area',
    subject: 'mathematics',
    category: 'Geometry',
    name: 'Circle Geometry Engine',
    formula: 'A = π r²',
    description: 'Dynamic expanding/contracting circle canvas with radius line and live area calculation.',
    parameters: [
      { symbol: 'r', name: 'Radius', unit: 'cm', defaultValue: 8, min: 1, max: 25 },
    ],
    equations: ['circle-area', 'circle-equation'],
    component: 'CircleAreaSim',
    keywords: ['circle', 'area', 'radius', 'geometry', 'pi', 'circumference'],
  },
  graph: {
    id: 'graph',
    subject: 'mathematics',
    category: 'Algebra & Functions',
    name: 'Quadratic & Function Grapher',
    formula: 'y = a x² + b x + c',
    description: 'Coordinate grid function grapher showing live vertex, real roots, and axis of symmetry.',
    parameters: [
      { symbol: 'a', name: 'Coefficient a', unit: '', defaultValue: 1, min: -5, max: 5 },
      { symbol: 'b', name: 'Coefficient b', unit: '', defaultValue: -2, min: -10, max: 10 },
      { symbol: 'c', name: 'Coefficient c', unit: '', defaultValue: -3, min: -10, max: 10 },
    ],
    equations: ['quadratic', 'linear-function', 'sine-function'],
    component: 'GraphSim',
    keywords: ['graph', 'quadratic', 'parabola', 'roots', 'vertex', 'algebra', 'function'],
  },
  geometry3d: {
    id: 'geometry3d',
    subject: 'mathematics',
    category: '3D Geometry',
    name: '3D Geometry WebGL Engine',
    formula: 'V = ⁴⁄₃ π r³',
    description: 'Interactive rotatable 3D sphere, cylinder, cone, and 3D vector fields with perspective projection.',
    parameters: [
      { symbol: 'r', name: 'Radius', unit: 'px', defaultValue: 60, min: 20, max: 120 },
      { symbol: 'h', name: 'Height', unit: 'px', defaultValue: 100, min: 40, max: 180 },
    ],
    equations: ['sphere-volume', 'cylinder-volume', 'cone-volume'],
    component: 'Geometry3DSim',
    keywords: ['3d', 'sphere', 'cylinder', 'cone', 'volume', 'geometry', 'surface area'],
  },
};

// Helper Functions for Subject-Aware Filtering
export function getSimulationsBySubject(subject: Subject): SimulationEntry[] {
  return Object.values(simulationMetadata).filter((sim) => sim.subject === subject);
}

export function getCategoriesBySubject(subject: Subject): string[] {
  const sims = getSimulationsBySubject(subject);
  const categories = new Set<string>();
  sims.forEach((sim) => categories.add(sim.category));
  return Array.from(categories);
}

export function getSimulationsByCategory(subject: Subject, category: string): SimulationEntry[] {
  return getSimulationsBySubject(subject).filter((sim) => sim.category === category);
}

export function searchSimulations(subject: Subject, query: string): SimulationEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return getSimulationsBySubject(subject);

  return getSimulationsBySubject(subject).filter(
    (sim) =>
      sim.name.toLowerCase().includes(q) ||
      sim.description.toLowerCase().includes(q) ||
      sim.category.toLowerCase().includes(q) ||
      (sim.formula && sim.formula.toLowerCase().includes(q)) ||
      sim.keywords.some((kw) => kw.toLowerCase().includes(q))
  );
}
